spring.application.name=api

# DB
spring.datasource.url=jdbc:mariadb://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:ec}
spring.datasource.username=${DB_USERNAME:ec_user}
spring.datasource.password=${DB_PASSWORD:ec_pass}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# MyBatis
mybatis.mapper-locations=classpath*:mapper/**/*.xml,classpath*:mapper/mbg/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.nagi4757.ec.api.infra.mbg.model

# Server
server.port=8080

# flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Auth/JWT
app.auth.jwt.secret=change-this-secret-at-least-32-bytes-long
app.auth.jwt.access-token-expiration-seconds=3600

# Redis (Cart)
spring.data.redis.host=${REDIS_HOST:127.0.0.1}
spring.data.redis.port=${REDIS_PORT:6379}

