# Database
spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# Actuator
management.endpoint.health.group.readiness.include=readinessState,db,redis

# Auth
app.auth.jwt.secret=${APP_AUTH_JWT_SECRET}

# CORS
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}

# Logging
logging.structured.format.console=ecs
logging.structured.ecs.service.environment=prod
