spring.application.name=api

# Database
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# MyBatis
mybatis.mapper-locations=classpath*:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# Server
server.port=8080

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Auth
app.auth.jwt.access-token-expiration-seconds=${APP_AUTH_JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:3600}
